import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { BeakerIcon } from "@heroicons/react/solid";
import { Switch } from "@headlessui/react";

const Home: NextPage = () => {
  const [enabled, setEnabled] = useState(false);

  return (
    <div>
      <Head>
        <title>Gemini</title>
        <meta
          name="description"
          content="Gemini Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <BeakerIcon className="h-5 w-5 text-blue-500" />

        <Switch
          checked={enabled}
          onChange={setEnabled}
          className={`${
            enabled ? "bg-blue-600" : "bg-gray-200"
          } relative inline-flex items-center h-6 rounded-full w-11`}
        >
          <span className="sr-only">Enable notifications</span>
          <span
            className={`${
              enabled ? "translate-x-6" : "translate-x-1"
            } inline-block w-4 h-4 transform bg-white rounded-full`}
          />
        </Switch>

        <div className="bg-blue-100 rounded shadow">My name is Jim</div>
      </main>
    </div>
  );
};

export default Home;
